#!/usr/bin/env python3
"""
NFT Monitor - Auto Installer (Universal)
Instalasi otomatis untuk semua platform (Windows, Linux, Mac)
"""

import os
import sys
import subprocess
import platform

# Warna terminal
class Colors:
    if platform.system() == 'Windows':
        # Windows doesn't support ANSI by default in older versions
        RED = ''
        GREEN = ''
        YELLOW = ''
        BLUE = ''
        NC = ''
    else:
        RED = '\033[0;31m'
        GREEN = '\033[0;32m'
        YELLOW = '\033[1;33m'
        BLUE = '\033[0;34m'
        NC = '\033[0m'

def print_header():
    """Print installer header"""
    print("\n" + Colors.BLUE)
    print("╔═══════════════════════════════════════════════════════════╗")
    print("║                                                           ║")
    print("║     NFT FREE MINT MONITOR - AUTO INSTALLER               ║")
    print("║              Instalasi Otomatis Lengkap                   ║")
    print("║                                                           ║")
    print("╚═══════════════════════════════════════════════════════════╝")
    print(Colors.NC + "\n")

def print_step(step, total, message):
    """Print step header"""
    print(f"\n{Colors.BLUE}[STEP {step}/{total}]{Colors.NC} {Colors.GREEN}{message}{Colors.NC}\n")

def print_success(message):
    """Print success message"""
    print(f"{Colors.GREEN}✓ {message}{Colors.NC}")

def print_error(message):
    """Print error message"""
    print(f"{Colors.RED}✗ {message}{Colors.NC}")

def print_warning(message):
    """Print warning message"""
    print(f"{Colors.YELLOW}⚠ {message}{Colors.NC}")

def check_python():
    """Check Python version"""
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 7):
        print_error(f"Python {version.major}.{version.minor} terlalu lama!")
        print("Minimal Python 3.7 diperlukan")
        print("Download: https://www.python.org/downloads/")
        return False
    
    print_success(f"Python {version.major}.{version.minor}.{version.micro}")
    return True

def install_dependencies():
    """Install Python dependencies"""
    print("Installing: requests, python-dotenv...")
    
    try:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "--user", "--quiet", 
             "requests", "python-dotenv"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )
        print_success("Dependencies terinstall")
        return True
    except subprocess.CalledProcessError:
        print_error("Gagal install dependencies")
        print("Coba manual: pip install requests python-dotenv")
        return False

def test_telegram(token, chat_id):
    """Test Telegram configuration"""
    import requests
    
    # Test bot API
    url = f"https://api.telegram.org/bot{token}/getMe"
    try:
        response = requests.get(url, timeout=10)
        if response.status_code != 200:
            print_error("Token tidak valid!")
            return False
        
        bot_info = response.json()
        username = bot_info.get('result', {}).get('username', 'Unknown')
        print_success(f"Bot: @{username}")
    except Exception as e:
        print_error(f"Koneksi gagal: {e}")
        return False
    
    # Send test message
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {
        'chat_id': chat_id,
        'text': '🎉 <b>NFT Monitor - Instalasi Sukses!</b>\n\n'
                '✅ Bot terinstall dengan benar\n'
                '✅ Siap monitoring NFT free mints\n\n'
                '<i>Instalasi selesai! Bot akan segera dimulai...</i>',
        'parse_mode': 'HTML'
    }
    
    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            print_success("Pesan test terkirim ke Telegram!")
            return True
        else:
            print_error(f"Gagal kirim pesan (Status {response.status_code})")
            return False
    except Exception as e:
        print_error(f"Error: {e}")
        return False

def create_env_file(token, chat_id):
    """Create .env configuration file"""
    content = f"""# NFT Monitor Configuration
# Auto-generated by installer

# REQUIRED: Telegram Bot Configuration
TELEGRAM_BOT_TOKEN={token}
TELEGRAM_CHAT_ID={chat_id}

# OPTIONAL: API Keys (kosongkan jika tidak ada)
OPENSEA_API_KEY=
TWITTER_BEARER_TOKEN=
MAGICEDEN_API_KEY=

# Monitoring Settings
CHECK_INTERVAL=5
MAX_PRICE=1.0
MIN_PUMP_SCORE=50
CHAINS=ethereum,polygon,solana
PLATFORMS=rarible,opensea,magiceden,foundation,zora

# Feature Toggles
INCLUDE_VOLUME=true
INCLUDE_HOLDERS=true
INCLUDE_SOCIAL_METRICS=true
"""
    
    with open('.env', 'w') as f:
        f.write(content)
    
    print_success("File .env dibuat")

def main():
    """Main installer function"""
    print_header()
    
    print(f"{Colors.GREEN}Installer ini akan:{Colors.NC}")
    print("  ✓ Mengecek sistem requirements")
    print("  ✓ Install dependencies otomatis")
    print("  ✓ Membuat konfigurasi Telegram")
    print("  ✓ Setup database")
    print("  ✓ Menjalankan bot")
    print()
    input(f"{Colors.YELLOW}Tekan ENTER untuk mulai instalasi...{Colors.NC}")
    
    # STEP 1: Check system
    print_step(1, 6, "Mengecek sistem requirements...")
    
    print(f"OS: {platform.system()} {platform.release()}")
    
    if not check_python():
        sys.exit(1)
    
    # STEP 2: Install dependencies
    print_step(2, 6, "Menginstall Python dependencies...")
    
    if not install_dependencies():
        sys.exit(1)
    
    # STEP 3: Setup Telegram
    print_step(3, 6, "Setup Telegram Bot...")
    
    print(Colors.YELLOW)
    print("════════════════════════════════════════════════════════")
    print("  SETUP TELEGRAM BOT")
    print("════════════════════════════════════════════════════════")
    print(Colors.NC)
    
    print()
    print(f"{Colors.GREEN}Langkah 1: Buat Telegram Bot{Colors.NC}")
    print("  1. Buka Telegram")
    print("  2. Cari: @BotFather")
    print("  3. Kirim: /newbot")
    print("  4. Ikuti instruksi")
    print("  5. Copy TOKEN yang diberikan")
    print()
    
    has_token = input(f"{Colors.YELLOW}Sudah punya TOKEN? (y/n): {Colors.NC}").strip().lower()
    
    if has_token != 'y':
        print()
        print(f"{Colors.YELLOW}Silakan buat bot Telegram terlebih dahulu!{Colors.NC}")
        print("1. Buka: https://t.me/BotFather")
        print("2. Kirim: /newbot")
        print("3. Jalankan installer ini lagi setelah dapat TOKEN")
        sys.exit(0)
    
    print()
    telegram_token = input(f"{Colors.GREEN}Masukkan TELEGRAM BOT TOKEN: {Colors.NC}").strip()
    
    if not telegram_token:
        print_error("Token tidak boleh kosong!")
        sys.exit(1)
    
    print()
    print(f"{Colors.GREEN}Langkah 2: Dapatkan Chat ID{Colors.NC}")
    print("  1. Cari: @userinfobot di Telegram")
    print("  2. Kirim: /start")
    print("  3. Copy ID yang muncul")
    print()
    
    chat_id = input(f"{Colors.GREEN}Masukkan TELEGRAM CHAT ID: {Colors.NC}").strip()
    
    if not chat_id:
        print_error("Chat ID tidak boleh kosong!")
        sys.exit(1)
    
    print_success("Telegram konfigurasi tersimpan")
    
    # STEP 4: Create .env
    print_step(4, 6, "Membuat file konfigurasi...")
    create_env_file(telegram_token, chat_id)
    
    # STEP 5: Test configuration
    print_step(5, 6, "Testing konfigurasi Telegram...")
    
    print("Mengirim pesan test ke Telegram...")
    if not test_telegram(telegram_token, chat_id):
        print_error("Test gagal - cek TOKEN dan CHAT_ID")
        sys.exit(1)
    
    # STEP 6: Choose version
    print_step(6, 6, "Memilih versi bot...")
    
    print()
    print(f"{Colors.YELLOW}Pilih versi bot:{Colors.NC}")
    print()
    print(f"  {Colors.GREEN}1.{Colors.NC} Basic Version")
    print("     - Monitor 3 platform (OpenSea, Magic Eden, Twitter)")
    print("     - Alert sederhana")
    print("     - Ringan & cepat")
    print()
    print(f"  {Colors.GREEN}2.{Colors.NC} Enhanced Version (RECOMMENDED)")
    print("     - Monitor 7+ platform (termasuk Rarible, Zora, Foundation)")
    print("     - Pump Score Analysis (prediksi 0-100)")
    print("     - Alert lengkap dengan metrics")
    print("     - Multi-chain support")
    print()
    
    version_choice = input(f"{Colors.YELLOW}Pilih (1/2) [default: 2]: {Colors.NC}").strip()
    
    if version_choice == '1':
        bot_script = 'nft_monitor_with_dotenv.py'
        print_success("Memilih: Basic Version")
    else:
        bot_script = 'nft_monitor_enhanced.py'
        print_success("Memilih: Enhanced Version dengan Pump Analysis")
    
    # Success!
    os.system('clear' if platform.system() != 'Windows' else 'cls')
    
    print(Colors.GREEN)
    print("╔═══════════════════════════════════════════════════════════╗")
    print("║                                                           ║")
    print("║              ✓ INSTALASI SELESAI!                        ║")
    print("║                                                           ║")
    print("╚═══════════════════════════════════════════════════════════╝")
    print(Colors.NC)
    
    print()
    print(f"{Colors.GREEN}Bot NFT Monitor siap digunakan!{Colors.NC}")
    print()
    print(f"{Colors.YELLOW}Informasi Setup:{Colors.NC}")
    print(f"  • Token: {telegram_token[:20]}...")
    print(f"  • Chat ID: {chat_id}")
    print(f"  • Versi: {'Enhanced' if 'enhanced' in bot_script else 'Basic'}")
    print(f"  • Config: .env")
    print()
    
    print(f"{Colors.YELLOW}Langkah selanjutnya:{Colors.NC}")
    print()
    print(f"{Colors.GREEN}Jalankan bot:{Colors.NC}")
    print(f"   python3 {bot_script}")
    print()
    
    print(f"{Colors.YELLOW}Dokumentasi:{Colors.NC}")
    print("  • Cara pakai: START_HERE_ENHANCED.txt")
    print("  • Keamanan: SECURITY_GUIDE.txt")
    print("  • Bahasa Indonesia: README_INDONESIA.txt")
    print()
    
    run_now = input(f"{Colors.YELLOW}Jalankan bot sekarang? (y/n): {Colors.NC}").strip().lower()
    
    if run_now == 'y':
        print()
        print(f"{Colors.GREEN}Menjalankan NFT Monitor...{Colors.NC}")
        print(f"{Colors.YELLOW}Tekan Ctrl+C untuk stop{Colors.NC}")
        print()
        
        import time
        time.sleep(2)
        
        try:
            subprocess.call([sys.executable, bot_script])
        except KeyboardInterrupt:
            print(f"\n{Colors.YELLOW}Bot dihentikan{Colors.NC}")
    else:
        print()
        print(f"{Colors.GREEN}Instalasi selesai!{Colors.NC}")
        print()
        print("Jalankan kapan saja dengan:")
        print(f"  {Colors.YELLOW}python3 {bot_script}{Colors.NC}")
        print()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n{Colors.YELLOW}Instalasi dibatalkan{Colors.NC}")
        sys.exit(0)
    except Exception as e:
        print(f"\n{Colors.RED}Error: {e}{Colors.NC}")
        sys.exit(1)
